<?
/**
 * Copyright (c) 5/12/2019 Created By/Edited By ASDAFF asdaff.asad@yandex.ru
 */

if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true)
    die();

if (!defined("WIZARD_TEMPLATE_ID"))
    return;

function QuickAddEvent($EventType, $EventTypeName, $EventDescription, $EventTemplateMessage, $EventTemplateSubjects, $EmailTo = "#DEFAULT_EMAIL_FROM#")
{

    $CEventType = new CEventType;
    $EventTypeIDCallback = $CEventType->Add(array(
            "LID" => "ru",
            "EVENT_NAME" => $EventType,
            "NAME" => $EventTypeName,
            "DESCRIPTION" => $EventDescription
        )
    );

    if ($EventTypeIDCallback > 0) {
        $arSites = array();
        $rsSites = CSite::GetList();
        while ($arSite = $rsSites->Fetch()) {
            $arSites[] = $arSite["LID"];
        }

        $Fields["ACTIVE"] = "Y";
        $Fields["EVENT_NAME"] = $EventType;
        $Fields["LID"] = $arSites;
        $Fields["EMAIL_FROM"] = "#DEFAULT_EMAIL_FROM#";
        $Fields["EMAIL_TO"] = $EmailTo;
        $Fields["BCC"] = "";
        $Fields["SUBJECT"] = $EventTemplateSubjects;
        $Fields["BODY_TYPE"] = "text";
        $Fields["MESSAGE"] = $EventTemplateMessage;

        $CEventMessage = new CEventMessage;
        $EventTemplateID = $CEventMessage->Add($Fields);
    }

}


//services
QuickAddEvent("QUICK_SERVICE_ORDER", GetMessage('QUICK_SERVICE_ORDER'), GetMessage('QUICK_SERVICE_ORDER_DESCRIPTION'), GetMessage('QUICK_SERVICE_ORDER_MESSAGE'), GetMessage('QUICK_SERVICE_ORDER_SUBJECT'));
QuickAddEvent("QUICK_SERVICE_ORDER_USER", GetMessage('QUICK_SERVICE_ORDER_USER'), GetMessage('QUICK_SERVICE_ORDER_USER_DESCRIPTION'), GetMessage('QUICK_SERVICE_ORDER_USER_MESSAGE'), GetMessage('QUICK_SERVICE_ORDER_USER_SUBJECT'), "#EMAIL_TO#");

QuickAddEvent("QUICK_SERVICE_QUESTIONS", GetMessage('QUICK_SERVICE_QUESTIONS'), GetMessage('QUICK_SERVICE_QUESTIONS_DESCRIPTION'), GetMessage('QUICK_SERVICE_QUESTIONS_MESSAGE'), GetMessage('QUICK_SERVICE_QUESTIONS_SUBJECT'));
QuickAddEvent("QUICK_SERVICE_QUESTIONS_USER", GetMessage('QUICK_SERVICE_QUESTIONS_USER'), GetMessage('QUICK_SERVICE_QUESTIONS_USER_DESCRIPTION'), GetMessage('QUICK_SERVICE_QUESTIONS_USER_MESSAGE'), GetMessage('QUICK_SERVICE_QUESTIONS_USER_SUBJECT'), "#EMAIL_TO#");


//catalog
QuickAddEvent("QUICK_CATALOG_ORDER", GetMessage('QUICK_CATALOG_ORDER'), GetMessage('QUICK_CATALOG_ORDER_DESCRIPTION'), GetMessage('QUICK_CATALOG_ORDER_MESSAGE'), GetMessage('QUICK_CATALOG_ORDER_SUBJECT'));
QuickAddEvent("QUICK_CATALOG_ORDER_USER", GetMessage('QUICK_CATALOG_ORDER_USER'), GetMessage('QUICK_CATALOG_ORDER_DESCRIPTION'), GetMessage('QUICK_CATALOG_ORDER_USER_MESSAGE'), GetMessage('QUICK_CATALOG_ORDER_USER_SUBJECT'), "#EMAIL_TO#");

QuickAddEvent("QUICK_CATALOG_QUESTIONS", GetMessage('QUICK_CATALOG_QUESTIONS'), GetMessage('QUICK_CATALOG_QUESTIONS_DESCRIPTION'), GetMessage('QUICK_CATALOG_QUESTIONS_MESSAGE'), GetMessage('QUICK_CATALOG_QUESTIONS_SUBJECT'));
QuickAddEvent("QUICK_CATALOG_QUESTIONS_USER", GetMessage('QUICK_CATALOG_QUESTIONS_USER'), GetMessage('QUICK_CATALOG_QUESTIONS_USER_DESCRIPTION'), GetMessage('QUICK_CATALOG_QUESTIONS_USER_MESSAGE'), GetMessage('QUICK_CATALOG_QUESTIONS_USER_SUBJECT'), "#EMAIL_TO#");

QuickAddEvent("QUICK_CATALOG_REVIEWS", GetMessage('QUICK_CATALOG_REVIEWS'), GetMessage('QUICK_CATALOG_REVIEWS_DESCRIPTION'), GetMessage('QUICK_CATALOG_REVIEWS_MESSAGE'), GetMessage('QUICK_CATALOG_REVIEWS_SUBJECT'));
QuickAddEvent("QUICK_CATALOG_REVIEWS_USER", GetMessage('QUICK_CATALOG_REVIEWS_USER'), GetMessage('QUICK_CATALOG_REVIEWS_USER_DESCRIPTION'), GetMessage('QUICK_CATALOG_REVIEWS_USER_MESSAGE'), GetMessage('QUICK_CATALOG_REVIEWS_USER_SUBJECT'));


//projects
QuickAddEvent("QUICK_PROJECTS_REVIEWS", GetMessage('QUICK_PROJECTS_REVIEWS'), GetMessage('QUICK_PROJECTS_REVIEWS_DESCRIPTION'), GetMessage('QUICK_PROJECTS_REVIEWS_MESSAGE'), GetMessage('QUICK_PROJECTS_REVIEWS_SUBJECT'));
QuickAddEvent("QUICK_PROJECTS_REVIEWS_USER", GetMessage('QUICK_PROJECTS_REVIEWS_USER'), GetMessage('QUICK_PROJECTS_REVIEWS_USER_DESCRIPTION'), GetMessage('QUICK_PROJECTS_REVIEWS_USER_MESSAGE'), GetMessage('QUICK_PROJECTS_REVIEWS_USER_SUBJECT'));

QuickAddEvent("QUICK_PROJECTS_ORDER", GetMessage('QUICK_PROJECTS_ORDER'), GetMessage('QUICK_PROJECTS_ORDER_DESCRIPTION'), GetMessage('QUICK_PROJECTS_ORDER_MESSAGE'), GetMessage('QUICK_PROJECTS_ORDER_SUBJECT'));
QuickAddEvent("QUICK_PROJECTS_ORDER_USER", GetMessage('QUICK_PROJECTS_ORDER_USER'), GetMessage('QUICK_PROJECTS_ORDER_USER_DESCRIPTION'), GetMessage('QUICK_PROJECTS_ORDER_USER_MESSAGE'), GetMessage('QUICK_PROJECTS_ORDER_USER_SUBJECT'), "#EMAIL_TO#");


//question answer
QuickAddEvent("QUICK_NEW_QUESTION", GetMessage('QUICK_NEW_QUESTION'), GetMessage('QUICK_NEW_QUESTION_DESCRIPTION'), GetMessage('QUICK_NEW_QUESTION_MESSAGE'), GetMessage('QUICK_NEW_QUESTION_SUBJECT'));
QuickAddEvent("QUICK_NEW_QUESTION_USER", GetMessage('QUICK_NEW_QUESTION_USER'), GetMessage('QUICK_NEW_QUESTION_USER_DESCRIPTION'), GetMessage('QUICK_NEW_QUESTION_USER_MESSAGE'), GetMessage('QUICK_NEW_QUESTION_USER_SUBJECT'));
//QuickAddEvent("QUICK_NEW_QUESTION_REPLY", GetMessage('QUICK_NEW_QUESTION_REPLY'), GetMessage('QUICK_NEW_QUESTION_REPLY_DESCRIPTION'), GetMessage('QUICK_NEW_QUESTION_REPLY_MESSAGE'), GetMessage('QUICK_NEW_QUESTION_REPLY_SUBJECT'), "#NEW_QUESTION_EMAIL_USER#");


//feedback
QuickAddEvent("QUICK_FEEDBACK", GetMessage('QUICK_FEEDBACK'), GetMessage('QUICK_FEEDBACK_DESCRIPTION'), GetMessage('QUICK_FEEDBACK_MESSAGE'), GetMessage('QUICK_FEEDBACK_SUBJECT'));
QuickAddEvent("QUICK_FEEDBACK_USER", GetMessage('QUICK_FEEDBACK_USER'), GetMessage('QUICK_FEEDBACK_USER_DESCRIPTION'), GetMessage('QUICK_FEEDBACK_USER_MESSAGE'), GetMessage('QUICK_FEEDBACK_USER_SUBJECT'));


//callback
QuickAddEvent("QUICK_CALLBACK", GetMessage('QUICK_CALLBACK'), GetMessage('QUICK_CALLBACK_DESCRIPTION'), GetMessage('QUICK_CALLBACK_MESSAGE'), GetMessage('QUICK_CALLBACK_SUBJECT'));
//QuickAddEvent("QUICK_CALLBACK_USER", GetMessage('QUICK_CALLBACK_USER'), GetMessage('QUICK_CALLBACK_USER_DESCRIPTION'), GetMessage('QUICK_CALLBACK_USER_MESSAGE'), GetMessage('QUICK_CALLBACK_USER_SUBJECT'));
?>